#!/usr/bin/env bash
# Configures Nginx to listen on port 80

# Install Nginx
apt-get update
apt-get install -y nginx

# Make sure Nginx is running and listening on port 80
sed -i 's/80 default_server/80 default_server;/g' /etc/nginx/sites-available/default
service nginx restart
