#!/usr/bin/env bash
# Fixing Nginx to listen on port 80 in 5 lines or less

sudo sed -i "s/8080/80/" /etc/nginx/sites-enabled/default
sudo service nginx restart
echo "" | sudo dd status=none of=/run/nginx.pid
